# Generated by Django 4.2.25 on 2025-10-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('mtn_money', 'MTN Mobile Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('cb', 'Carte Bancaire'), ('cash', 'Espèces'), ('paypal', 'PayPal')], default='orange_money', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='receipt_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, help_text='Localisation du produit', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_address',
            field=models.TextField(blank=True, help_text="Adresse de l'entrepôt"),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('dark', 'Sombre'), ('light', 'Clair'), ('mystery', 'Mystérieux')], default='mystery', max_length=20),
        ),
    ]
