# Generated by Django 4.2.25 on 2025-10-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_payment_method_order_payment_reference_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receipt_sent',
        ),
        migrations.RemoveField(
            model_name='product',
            name='location',
        ),
        migrations.RemoveField(
            model_name='product',
            name='warehouse_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='theme',
        ),
    ]
