# Generated by Django 4.2.25 on 2025-10-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_order_receipt_sent_remove_product_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(blank=True, help_text='Localisation du produit', max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_address',
            field=models.TextField(blank=True, help_text="Adresse de l'entrepôt"),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=5),
        ),
        migrations.AddField(
            model_name='user',
            name='theme',
            field=models.CharField(choices=[('dark', 'Sombre'), ('light', 'Clair'), ('mystery', 'Mystérieux')], default='mystery', max_length=20),
        ),
    ]
