# Generated by Django 4.2.25 on 2025-10-29 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_shop_alter_order_payment_method_user_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shop',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
